### ISSUE TITLE
relation operators

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#10]
Shen [[P0820R1](https://wg21.link/p0820r1)] argues for a substantial change to the definition of relation operators.
Kretz [[P0851R0](https://wg21.link/p0851r0)] presents the reason for the status quo. The choices were:
1. All relops are defined and return `simd_mask` (status quo).
2. Compares returning `simd_mask` are provided via new functions (member vs.
non-member?)
a) No relops are defined.
b) `operator==` and `operator!=` are defined and return `bool`.

If there is new information showing that the current behavior is problematic and a
different behavior is more useful the discussion should be reopened.

**Comment by iburyl** [comment]
Small correction. Relation operators discussion was in P0820R0 and it was removed from P0820R1.

**Comment by mattkretz** [comment]
I believe this question is settled: no change to the TS behavior necessary
