### ISSUE TITLE
The name of the hmin and hmax reduction functions is not intuitive

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#16]
Ideas:
* `inner_min(simd)`
* `reduce_min(simd)`
* `min_reduce(simd)`
* `min_element(simd)`
* `simd.min()`

**Comment by Pennycook** [comment]
I'd like to add another idea:
```c++
reduce(simd, minimum<>());
```
where `minimum` is defined similarly to `plus`, `multiplies` etc.  This is the design that we settled on for some of the [group collectives in DPC++](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/GroupAlgorithms/SYCL_INTEL_group_algorithms.asciidoc#function-objects).  Things we liked about it:
- No special-casing of function name required for min and max reductions
- The functor can be re-used by other interfaces expecting a binary operator (e.g. `std::reduce`)

**Comment by mattkretz** [comment]
I agree. Interestingly, with C++20 there's `std::ranges::min` (and `max`) which come close. But not close enough, so that they can't work (i.e. they return the result by const-ref, inhibiting a result that is combined from both inputs). `std::min` is already taken and overloaded for `simd`. So all we need is a `std::minimum` that is to `min` what `std::plus` is to `+`. I'll have to explore this in the paper. Let's see what WG21 can agree on.

**Comment by ibaned** [comment]
I'm implementing a subset of this and will go with `reduce(where(mask, values), minimum<>())`.

**Comment by mattkretz** [comment]
@danieltowner What do you think about Section 5.1 in [D1928R3.pdf](https://github.com/mattkretz/std-simd-feedback/files/10537621/D1928R3.pdf)?

**Comment by mattkretz** [comment]
Renamed to `reduce_min` and `reduce_max` by LEWG.
