### ISSUE TITLE
<cmath> operations

### ISSUE THREAD

**Issue by ibaned** [mattkretz/std-simd-feedback#18]
It would be useful to provide overloads of operations like `std::sqrt` that work with `simd` types. He is a non-exhaustive list of non-member operations we provide in [our attempt](https://github.com/kokkos/simd-math) that are desired by our users:

1. `std::sqrt`
2. `std::sin`
3. `std::cos`
4. `std::exp`
5. `std::log`
6. `std::pow`
7. `std::copysign`
8. `std::fma`
9. `std::cbrt`

Implementations can just fall back to calling the existing scalar operations. Note that `std::fma` and `std::cbrt` can be implemented by calling the Vector Mathematical Functions of the Intel Math Kernel Library on Intel platforms.

**Comment by ibaned** [comment]
@crtrott @dalg24

**Comment by mattkretz** [comment]
Like so: https://godbolt.org/z/hqGWej ? The TS already requires `simd` overloads for all of `<cmath>`. My libstdc++ implementation currently explicitly vectorizes the classification functions and sin & cos. IIUC what you're asking for is already provided. So in a sense you're giving feedback that it's important to have those overloads.

**Comment by ibaned** [comment]
Great! I wasn't aware it was already provided, so yes this amounts to confirming how important those are for our scientific computing applications.
