### ISSUE TITLE
Inconsistent use of size_t and int for sizes or indexes

### ISSUE THREAD

**Issue by danieltowner** [mattkretz/std-simd-feedback#33]

**Comment by mattkretz** [comment]
`int` for indexes?

`int` is used in the TS for
* `fixed_size`,
* `max_fixed_size`,
* `resize_simd`,
* the RHS argument of `<<` and `>>`, and
* the return type of non-bool mask reductions.

Did I miss anything?

Of those, I would change `fixed_size`, `max_fixed_size`, and `resize_simd` to use `size_t` instead. It's highly unlikely that `simd::size` can be turned into an `int`. But `size` and the size template parameters have no reason for not being consistent, I think.

The `int` never has come up as a problem for me. But it's surprising.

**Comment by mattkretz** [comment]
https://github.com/mattkretz/wg21-papers/commit/3b2216a79a1ebdc74bcfb9aacd8e7cf022186dfc

**Comment by rarutyun** [comment]
> `int` for indexes?
> 
> `int` is used in the TS for
> 
> * `fixed_size`,
> * `max_fixed_size`,
> * `resize_simd`,
> * the RHS argument of `<<` and `>>`, and
> * the return type of non-bool mask reductions.
> 
> Did I miss anything?
> 
> Of those, I would change `fixed_size`, `max_fixed_size`, and `resize_simd` to use `size_t` instead. It's highly unlikely that `simd::size` can be turned into an `int`. But `size` and the size template parameters have no reason for not being consistent, I think.
> 
> The `int` never has come up as a problem for me. But it's surprising.

I probably misunderstood that comment but looking into https://web-docs.gsi.de/~mkretz/D1928.pdf I cannot find any mentioning of `int` in Formal Wording.

Is this correct statement that you drop `int` from everywhere and now we have `std::size_t` in the paper?

**Comment by mattkretz** [comment]
Yes. You can see it in Section 6.2 (Diff against the TS) where I replaced `int` with `size_t`.

**Comment by mattkretz** [comment]
accepted by LEWG
