### ISSUE TITLE
Naming of masked overloads for copy_to, copy_from, ctor, reduce, etc.

### ISSUE THREAD

**Issue by danieltowner** [mattkretz/std-simd-feedback#35]
I think that the names of the copy_to/from functions, reduuctions, and so on should be left as-is, and an extra mask parameter added to provide an overload.

I don't like adding the _if suffix to the functions because that makes them too similar to existing functions which have a different behaviour. For example, copy_if only copies values to the destination if the predicate is met, so it has the effect of compressing the data too, For example, if the predicate matched 3 out of 6 values from an input iterator, then the output will only have 3 values. But the copy_to/copy_from are actually doing the equivalent of ``*this = mask ? *ptr : *this`` which applies the mask bit in place.

If you wanted to change the name, then I suggest using a variant of the word mask in the name instead, to make it clear that this is an in-place mask that is being applied, not a C++ copy_if compression.

I think having a ``copy_if`` function that works on simd would be useful, but it should behave like its C++ counterpart and perform compression.

**Comment by mattkretz** [comment]
This is an open question in [D1928R3.pdf](https://github.com/mattkretz/std-simd-feedback/files/10558448/D1928R3.pdf) to get feedback from LEWG. I.e. this is a new function / different design than was previously voted through LEWG. So they'll have to look at it in any case. We'll discuss it next Wednesday.

**Comment by mattkretz** [comment]
LEWG voted to overload on the same name and order arguments as `(simd, mask, <defaulted arguments>)`

**Comment by mattkretz** [comment]
loads, stores, and reductions don't use `where_expression` anymore in R4
