### ISSUE TITLE
produce "modern" wording, deleting the diff

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#43]

**Comment by JeffGarland** [comment]
@mattkretz I can help with this -- I haven't done much tex lately, but I can get it setup. You want pull requests on this file? https://github.com/mattkretz/wg21-papers/blob/master/P1928/wording2.tex

**Comment by mattkretz** [comment]
@JeffGarland that'd be great. The file to work on is: https://github.com/mattkretz/wg21-papers/blob/master/P1928/wording.tex. But let me remove the diff first before you start. I'll ping you here when it's ready.

**Comment by JeffGarland** [comment]
Ok great.

**Comment by mattkretz** [comment]
@JeffGarland `wording.tex` is stripped of all diff macros now.
