### ISSUE TITLE
discuss why not to pull split and concat — potentially pull parts of split?

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#50]
to be discussed (and possibly re-added) in a paper discussing `extract`, `insert`/`replace`, `resize`

**Comment by mattkretz** [comment]
@danieltowner You mentioned the use of `concat` in some of your `permute` examples. Do you think it makes sense to discuss (and readd) `concat` in the context of P2664?

One permutation I encounter frequently is the need to "palignr" two registers. This could be implemented via `permute<a.size()>(concat(a, b), shift_by<1>)`. But without `concat` it seems `permute` would need multi-simd input support (which leads to better code-gen with GCC, BTW).

Update: I can resolve the GCC code-gen issue. So `concat` seems like a reasonable tool in combination with `permute`.

**Comment by danieltowner** [comment]
Recently I have found that both concat and split_by can actually be pretty useful. I think we should keep concat to be able to handle multi-input permute without a variadic permute being needed and I think split_by is useful for operations in matrix processing, which break things down into regular blocks of simd and iterate over them. The split<X, Y, Z> is probably the least used of that family of functions and the one that extract most easily replaces.

**Comment by danieltowner** [comment]
I will write this up as a paper.

**Comment by mattkretz** [comment]
What else besides the remaining `simd_cat` and the new `simd_split` function do you want? I was about to close this issue as done.

**Comment by danieltowner** [comment]
Maybe I commented in the wrong place. The committee originally wanted a wider discussion paper on adding insert, extract, resize, etc. and how they work along side or replace some uses of split and concat.

**Comment by mattkretz** [comment]
Ah, got it now. Yes, better track extract, insert/replace, resize in a different issue. This was meant to remind me about pulling split and concat from P1928. Which didn't happen.
