### ISSUE TITLE
Provide more overload set restrictions for element type

### ISSUE THREAD

**Issue by danieltowner** [mattkretz/std-simd-feedback#54]
There are already some restrictions on operators/functions to remove them from overload set where they don't apply to the value_type but there are some places where these restrictions seem to be missing:

operator++,--
operator!
relational operators: <, <=, >, >=
hmin/hmax (or their equivalent new names) must support relational types (which complex isn't).
min/max/clamp

**Comment by danieltowner** [comment]
Note: this would be necessary for complex<> as a value_type, but would also pave the way for user-defined types too.

**Comment by mattkretz** [comment]
I agree. It's not necessary to have in P1928, but why not. Maybe I can add something general to apply to all operations.
