### ISSUE TITLE
Should there be a masked load constructor overload?

### ISSUE THREAD

**Issue by danieltowner** [mattkretz/std-simd-feedback#56]
A user requested that loads from contiguous iterations should allow a mask, to match the behaviour of copy_from:

    template<contiguous_iterator It, class Flags = element_aligned_tag>
    constexpr simd(It begin, mask_type mask, Flags = {});

**Comment by danieltowner** [comment]
Fixed in https://github.com/mattkretz/wg21-papers/commit/bdf75a4eba5283e7a732fd9d774883c2273e29f8

**Comment by mattkretz** [comment]
Yes, I was recently doing masked loads and wanted the object to be `const`. A constructor that value-inits the rest is the most reasonable choice here.
