### ISSUE TITLE
Reconsider conversion rules

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#65]
@mpusz made a good point recently that `simd` shouldn't mess with inventing new conversion rules for existing types. I.e. just let `simd<T>` convert to `simd<U>` if `T` is convertible to `U` and the SIMD width matches.
Rationale: we probably will invent library types sooner or later that provide stricter conversion rules on top of built-in arithmetic types. Once we have them `simd<safer<int>>` will be a thing. And then we'll have a mess of inconsistency.

@danieltowner Opinions?

Context: the current rules were a wish of SG1 back in 2014/15 (?) that I implemented.

**Comment by danieltowner** [comment]
Agreed. I don't think its simd's place to change the rules.

**Comment by mpusz** [comment]
Although it could be nice to have a type trait like `value_preserving<T, U>` that specifies it is "safe" to convert from type `T` to `U`. With this, a converting constructor could use `explicit(!value_preserving<T, U>) ...` so implicit conversion would be allowed for "safe" operations, and explicit one required when data truncation can happen.

I could benefit from it in my physical library as well. For now, I am cloning `std::chrono::duration` usage of [`treat_as_floating_point`](https://en.cppreference.com/w/cpp/chrono/treat_as_floating_point), which is a suboptimal solution.

**Comment by mattkretz** [comment]
* P2509R0 "A proposal for a type trait to detect value-preserving conversions" is that trait.
* The latest `simd` paper follows `explicit(!value_preserving<T, U>)`
* But I think we want a `value_preserving<T>` numeric type that has that behavior and then make `simd<value_preserving<T>>` have the conversion rules it has now.

**Comment by mpusz** [comment]
I think we need both ;-)

If fundamental types are used, the type trait would be nice to decide if the conversion should be implicit or explicit. If we get a safe wrapping numeric type, then we should just do what it does for such cases. However, this will not make fundamental types go away and we still will have to deal with them, so the first solution will still be needed.

**Comment by mattkretz** [comment]
I'm not sure I understand your point. Are you saying `simd<T>` should impose stricter conversion rules than `T` (for arithmetic `T`), using `explicit(!value_preserving<T, U>)`?

If you mean we need the trait and the type, then yes. The type should build upon the trait.

**Comment by mpusz** [comment]
> Are you saying simd<T> should impose stricter conversion rules than T (for arithmetic T), using explicit(!value_preserving<T, U>)?

This is the case for `std::chrono::duration`:

```cpp
// seconds d1 = 1.23s; // ERROR
seconds d2 = duration_cast<seconds>(1.23s);
duration<double> d3 = 123s;
```

- integral -> floating-point is considered a non-truncating conversion
- floating-point -> integral is definitely truncating

chrono decided to go with an explicit cast function (we do the same in mp-units), but simd could use an `explicit(true)` operator for "unsafe" conversions.

**Comment by mattkretz** [comment]
Note, that there's no easy / obvious solution so that binary operations "just work". I.e. if we have
```
template <class T>
class simd {
  simd(U);
  simd(simd<U>);
  friend simd operator+(simd, simd);
};
```
then the conversions defined by broadcast and conversion ctor determine the common type of binary operators. Interconvertible types lead to ambiguity - i.e. nothing working, everything needs explicit casts.
So, if we really want to make `simd` interconvertible in all directions then we need to change how binary operators work. Specifically, we need to implement [[expr.arith.conv]](https://eel.is/c++draft/expr.arith.conv) for binary operators but with the exception to *not do integral promotions*. So a simple `decltype(declval<T>() + declval<U>())` doesn't work.

Instead of implementing [expr.arith.conv] on the binary operators we could also turn these rules into the condition for `explicit` on broadcast and conversion ctor. If we do that, we have no literals for initializing `simd<short>` etc.

Either way, we simply cannot just follow the behavior of the builtin arithmetic types. We have to do invent some rules on top of `convertible_to` and `common_type_t`.

@mpusz Thinking about simd + units integration here: `simd<length>` could only work if every operation accepts different types (i.e. doesn't require conversion to a common type before calling the binary operator) and determines the return type from application of the relevant operator on the element types. Until you do masked reductions using `std::multiplies<>`... (the number of multiplications is determined at run-time).

**Comment by mpusz** [comment]
Yes, interconvertibility sucks. I had the same issue. The solution is to get rid of the ambiguity of binary operations is to make non-member non-friend binary operators:

```cpp
template<typename T, typename U>
simd<decltype(declval<T>() + declval<U>())> operator+(simd<T>, simd<U>);
```

or find a way to provide the conversion in only one direction.

> doesn't require conversion to a common type before calling the binary operator

Unfortunately, I need to convert to a common type for addition before doing it. This helps prevent some data truncation while scaling the value to a common unit.

**Comment by mattkretz** [comment]
Your non-member non-friend binary operator would not work for two `std::reference_wrapper<simd<T>>` arguments, whereas the hidden friend is found via ADL. So to get the same behavior we'd need a non-member `operator+(T, T)` + constraints. :-1:

But I believe it should be possible to also implement it as a hidden friend. It has mind-boggling corner cases - but they can be fixed.

> Unfortunately, I need to convert to a common type for addition before doing it. This helps prevent some data truncation while scaling the value to a common unit.

That seems to be a clear indication that we want `unit<simd>` and not `simd<unit>`, no?

**Comment by mpusz** [comment]
> That seems to be a clear indication that we want unit<simd> and not simd<unit>, no?

Both are fine for me ;-) (if only implementable).
ISO 80000 explicitly states that a quantity of vector and vector of quantities is a thing. I am not sure if SIMD should be perceived in terms of vector quantities as well,l or just to vectorize the computation on scalar quantities.

**Comment by mpusz** [comment]
> Your non-member non-friend binary operator would not work for two std::reference_wrapper<simd<T>> arguments, whereas the hidden friend is found via ADL. So to get the same behavior we'd need a non-member operator+(T, T) + constraints. 👎

I would love to ask you to provide feedback on mp-units interfaces when I am done with V2 🙏🏻

**Comment by mattkretz** [comment]
If ISO 80000 talks about a vector does it mean a container type (C++ vector) or a product type (math vector). SIMD is neither of those (P0851)...

**Comment by mpusz** [comment]
> If ISO 80000 talks about a vector does it mean a container type (C++ vector) or a product type (math vector). SIMD is neither of those (P0851)...

LOL 🤣 ISO 80000 does not know anything about C++ and especially `std::vector`. It talks about vector quantities like force or velocity. It also says explicitly that quantities may have scalar, vector, or tensor characteristics. And yes, I assume that SIMD is not a pure representation type for a `vector` quantity, but I am wondering if someone would not like to use it that way?

**Comment by mattkretz** [comment]
That's what I assumed. Just making sure...

`simd<T>` might be used in the implementation of vector/tensor operations but it probably won't appear on, much less *be* the interface of such types.

**Comment by mattkretz** [comment]
Please let me know whether this new section makes sense to you. (PDF here: https://web-docs.gsi.de/~mkretz/D1928.pdf)

**Comment by danieltowner** [comment]
I think I see the meaning but an example showing how the different options might affect a piece of code, and the knock-on effects on code generation and performance would make things clearer. In particular, I am very keen to avoid anything that silently degrades performance; I would prefer that code didn't compile at all if the types couldn't be aligned properly, rather than having the rules allow the code to compile but with nasty performance side effects.

**Comment by mattkretz** [comment]
I've been exploring the "choice 3" conversion behavior in some prototype code. I should be able to create a before/after table like:

|operand1|operand2|R4 result|common-type result|
|---|---|---|---|
|`int`|`simd<float>`|`simd<float>`|`simd<float>`|
|`long`|`simd<float>`|error|`simd<float>`|
|`simd<float>`|`simd<double>`|`simd<double>`|`simd<double>`|

would that help?

**Comment by danieltowner** [comment]
Yes, that would help.

**Comment by danieltowner** [comment]
Thanks for adding the tables.

I'm not convinced that any sort of conversion should happen automatically. If the user added two types of different sizes then performance will silently halve in comparison to if they had added two values of the smaller size.  For a performance library, such a big hit seems a bad choice. If it is an error to add incompatible types then the programmer will have to think about how to resolve the issue, and will be more aware of the conversion costs that they are incurring.

You list option 1 but never list the reasons to dismiss it or have a poll on it. But then I think that the wording of option 1 is unclear. By `consistently wrong' do you mean that incompatible types in operators should generate an error? If so, I can't see why that leads to subtle conversion issues, performance problems or complicated operators. So I think you mean something else.

**Comment by mattkretz** [comment]
> By `consistently wrong' do you mean that incompatible types in operators should generate an error?

Oh, that was a bad way of reusing a quote from the Issaquah polls "N: I would rather be consistently wrong than inconsistent". So I was trying to understand for myself what this "consistently wrong" (i.e. consistent with the behavior of builtin types) would be.

> You list option 1 but never list the reasons to dismiss it or have a poll on it.

Right. Basically, consistent with builtin types means `simd<char> + simd<char>` yields `simd<int>`. At that point I dismissed the idea and moved on to saner variations of it.

> I'm not convinced that any sort of conversion should happen automatically.

Meaning you like the TS rules and would make them even stricter, removing the conversions between fixed_size simds?

I found my code littered with casts - and very verbose at that even. Certain codes would have more characters used for casting than for the actual logic it was doing. That's not reasonable.

> If the user added two types of different sizes then performance will silently halve in comparison to if they had added two values of the smaller size.

I thought we discussed that point enough last time; we consider this "safe enough":
```c++
simd<float> x = ...;
rebind_simd_t<double, simd<float>> y = ...;
y = x + y; // OK: only one conversion from float to double, which is implicit
x = x + y; // ERROR: conversion from double to float needs cast
```

You would get this behavior from choice 2-4 in the paper - but not for choice 1.

**Comment by danieltowner** [comment]
> > I'm not convinced that any sort of conversion should happen automatically.
> 
> Meaning you like the TS rules and would make them even stricter, removing the conversions between fixed_size simds?

Yes and no. I do think that having some conversion happen automatically makes for saner code and that can only be a good thing. By making it easy for users it also means they are more likely to actively use std::simd, which I think brings an overall benefit to the community (better than non-portable intrinsics, probably faster than auto-vectorised scalar code, etc.). But I also don't want to trip up users by allowing them to easily and substantially degrade performance without realising it. I think the status quo is probably a reasonable balance though, so I think I'd be okay with some conversions.

> I found my code littered with casts - and very verbose at that even. Certain codes would have more characters used for casting than for the actual logic it was doing. That's not reasonable.

If having code littered with verbose casts is the issue, how about making casting easier to express? This was partially my thinking behind https://github.com/mattkretz/std-simd-feedback/issues/34 too. For a while I also implemented ```as<T>``` method which was used like this:

```cpp
simd<float> sf;
simd<int> si;

auto output = sf.as<int> * si;
```

Obviously as a method you couldn't apply that to scalar code, and if you go down the ```std::value_cast``` route then verbosity creeps back in.

**Comment by mpusz** [comment]
BTW, I followed your recommendation to name a function `value_cast` in mp-units:

https://github.com/mpusz/units/blob/41484742ae5e8c1c624e194bb558cb5cd047f370/example/avg_speed.cpp#L117-L118

**Comment by mattkretz** [comment]
> how about making casting easier to express?

P1928 makes it much easier by adding the conversion ctor implicit & explicit. The `as<T>` interface is still something useful that's missing, I agree. As you say, it can't be generic as a member function. And if `sf` has a dependent type you'd have to write `sf.template as<int>`, which is nasty.

@mpusz I was not expecting to see `value_cast<si::metre>(distance)`, because `value_cast` should only change the `value_type`, like `const_cast` can only change const-ness (and volatile-ness, but details).

**Comment by mpusz** [comment]
It affects the value being stored (i.e. truncates the value) exactly the same as I would cast from `double` to `int`.

**Comment by mpusz** [comment]
> And if sf has a dependent type you'd have to write sf.template as<int>, which is nasty.

Exactly, please do to go this path. This is why `std::get()` is not a member of `std::tuple`.

**Comment by mattkretz** [comment]
The exceptions for `int` and `unsigned int` on broadcast were removed by LEWG, otherwise no change.
