### ISSUE TITLE
Are VLS sve (risk v5) outside of the scope?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [mattkretz/std-simd-feedback#67]
If I'm understanding correctly, these are out of the scope for now. 
Which is absolutely fine by me since noone has any expirience and we can use fixed size (at least sve guarantees 16 bytes and neon is also present there) (don't know about risk-v5 but if they want to do WASM they better do risk-v5).

Question:
* Is it really out of scope?
* Have you thought about future enabling default to be runtime register size?

**Comment by mattkretz** [comment]
https://wg21.link/p0349 is my paper on the topic back when SVE was about to be unveiled. Short: as long as C++ has no solution for VLAs in the type system, I don't think we need to "waste" our time thinking about runtime-sized SIMD types. The strength of SIMD types is type vectorization, as I like to call it; and if that's what we'd have to pay to support the "scalable" in SVE, then it's not worth the cost.

**Comment by DenisYaroshevskiy** [comment]
Ok -  future standard committee will have a problem with not being able to change the default but I'm ok with that.
