### ISSUE TITLE
non power of 2 fixed_size

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [mattkretz/std-simd-feedback#73]
Hi

I know that Vc supported that and I think smth else.
Can I ask:

a) what's the usecase for non power of 2 fixed sizes
b) how's load/store implemented if masked operations are not avaliable?

**Comment by mattkretz** [comment]
Vc actually didn't support it in its `Vc::Vector` type. It had a `Vc::SimdArray` for it.

a) Use case: e.g. there's exactly 12 values that can be process in parallel. Let the user say 12 and the implementation, depending on target flags, uses 3x XMM, YMM + XMM, or implicitly masked ZMM. The user encodes his constraints without nailing down implementation details.

b) `std::memcpy`

**Comment by DenisYaroshevskiy** [comment]
That memcpy is slow to the point of useless here

**Comment by mattkretz** [comment]
That's an issue compilers need to fix. The point of the API is to communicate *more* information about the actual problem and its inherent parallelism. As long as such an API doesn't exist there's little incentive and test cases for compilers to improve.
