### ISSUE TITLE
What type should be used for generator index parameter?

### ISSUE THREAD

**Issue by danieltowner** [mattkretz/std-simd-feedback#83]
The draft allows the implementation to choose the index type using ```simd-size-type```, and this is used in places like `operator[](simd-size-type)`.

The generator constructor has the effect that the i'th element is set to ```gen(integral_constant<size_t, i>())```. Should this also match the implementation's data type - ```gen(integral_constant<simd-size-type, i>())```?

The disadvantage of doing that would be to make it hard to write a compile-time generator which worked on implementations which chose different `simd-size-type`s. Fixing it to a specific type (like size_t which can properly represent any possible index) is likely more useful, but is possibly slightly inconsistent with allowing the implementation to choose `simd-size-type`.

**Comment by mattkretz** [comment]
IIUC the direction from LEWG correctly, then the poll decided to change the generator argument from `integral_constant<size_t, i>` to `integral_constant<simd-size-type, i>`. And I simply overlooked it when updating the draft.

I don't understand your argument for why *simd-size-type* would have a disadvantage. This type must be able to represent all possible `simd` indexes in any case. An expression that adds a `size_t` offset for indexing into a larger array should always result in a `size_t` and thus also work correctly.

I see this portability pitfall: `simd<int>([](auto i) { return i; }` compiles if *simd-size-type* is `int` but doesn't compile if it's `int64_t`. Is that what you mean?

**Comment by danieltowner** [comment]
> I see this portability pitfall: `simd<int>([](auto i) { return i; }` compiles if _simd-size-type_ is `int` but doesn't compile if it's `int64_t`. Is that what you mean?

I was thinking what would happen if the user created a generator which explicitly had an integral constant argument:

```
struct IotaGenerator
{
  template<size_t IDX>
  auto operator()(std::integral_constant<size_t, IDX> i) const { return i & ~1u; }
};
```

When the implementation has chosen to make `simd-size-type`  map to `size_t` this will work, but it won't if a different type is used. If the generator moved to a different implementation this breaks. Maybe this would never realistically happen though, if users will tend to use `auto` arguments in their generators.

**Comment by mattkretz** [comment]
simple solution:
```c++
struct IotaGenerator
{
  template<typename T, size_t IDX>
  auto operator()(std::integral_constant<T, IDX> i) const { return i & ~1u; }
};
```

**Comment by mattkretz** [comment]
Also, I'd prefer if there was a concept for this `(std::constexpr_value<int> i)` (see https://github.com/mattkretz/constexpr_t/blob/main/include/constexpr_t.hpp#L18-L21)

**Comment by danieltowner** [comment]
I agree there are ways to avoid it. I just thought I'd highlight it anyway.

I was mostly interested in knowing if the `size_t` in the spec was an oversight, which you have clarified that it was.
