### ISSUE TITLE
converting loads/stores need a flag unless value-preserving

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#9]
Since implicit conversions on broadcasts are restricted to value-preserving conversions, the load/store interface is inconsistent with this strictness. I.e.:
```cpp
using V = simd<float>;
V(1.); // error, double -> float conversion is not value-preserving
V(short(1)); // good, short -> float is value-preserving
double mem[V::size()] = {1.};
V(mem, flags::element_aligned); // converting load, compiles (but shouldn't?)
short mem[V::size()] = {1};
V(mem, flags::element_aligned); // value-preserving conversion, compiles
```
The conversion is not obvious when you look at the line of code that requests the load.
Options:
1. Drop converting loads and stores. (That would be unfortunate, since doing converting loads and stores efficiently and portably is potentially a hard problem.)
2. Use different functions, e.g. `v.copy_from(mem, flags)` requires `mem` to be a `value_type` array. `v.memload_cvt_safe(mem, flags)` allows value-preserving conversions. `v.memload_cvt_unsafe(mem, flags)` allows all conversions.
3. Use a flag to enable conversions (without cvt flag, no conversions are allowed), e.g.
```cpp
V(mem, flags::element_aligned | flags::safe_cvt);
V(mem, flags::element_aligned | flags::any_cvt);
V(mem, flags::element_aligned | flags::saturating_cvt); // new feature
```

As a variation, safe conversions could be enabled per default and only unsafe
conversions would require extra typing.

**Comment by iburyl** [comment]
We should be consistent with what is expressible in scalar C++ code and not try to invent something new just for the vector. And vector code should be as close to scalar as possible.

Scalar equivalent for loading conversion is implicit form:
```c++
float *in;
int scalar{ in[0] };
stdx::native_simd<int> v{ in, stdx::element_aligned_tag{} };
```
Implicit conversion should better be identical to scalar version with exact same result.
Alignment flag is specific for simd, but conversion is not.

If there is need for safer version, we should agree on the scalar form first and then try to apply similar approach to `std::simd`.

What is current scalar analog for `safe_cvt`?
What is current scalar analog for `saturating_cvt`?

**Comment by mattkretz** [comment]
I think the analogy to scalar "loads" doesn't really hold. `int x = in[0];` is just a simple conversion like `int x = y;`. Whether the `int` on the rhs is the result of a non-trivial expression or simply an lvalue makes no difference. In any case the scalar analog for `safe_cvt` would be `int x{y}`.

I believe a closer analogy would be `std::copy`:
```c++
int a[N];
double b[N];
std::copy(std::begin(b), std::end(b), std::begin(a));
```
That doesn't really tell us enough wrt. the design consistency of `simd`. After all the conversions restrictions built into `simd` already are not consistent with how builtin types behave. This was a deliberate choice of the committee when P0214 was reviewed. Restricting conversions on loads and stores was simply never discussed (IIRC) and is inconsistent with the rest of `simd` - which is already inconsistent with builtin types.

Does that change your opinion?

**Comment by iburyl** [comment]
What was the argument for making conversions inconsistent with builtin types?
If we find an alternative way to make the existing behavior, may we rule back the consistent behavior as the default one?

**Comment by mattkretz** [comment]
```c++
simd<float> x = ...;
auto y = x + 1.2;  // ill-formed
```
Should the `double` convert implicitly to `simd<float>`? I guess you agree the answer is no. OTOH
```c++
simd<double> x = ...;
auto y = x + 1.2f;  // OK
```
is fine because converting `1.2f` to `double` /  `simd<double>` is safe.

```c++
float x = ...;
auto y = x + 1.2;  // y is double
```
This is not the behavior we want from `simd`, where it would have to implicitly widen to more registers than it needed before.

**Comment by iburyl** [comment]
I am not sure that those examples reveal the "load" concept:
`std::copy` - example is more of memory-memory operation.
scalar to `std::simd` - is about implicit conversion and not about loading.

When we are talking about load from memory the closest analog is
```
double* data;
float x{data[0]};
```
We are putting memory into scalar from memory.
There are three operations here - first subscript operator data[0] then implicit converting then constructing scalar.
If we want - non implicit conversion - we type it with a separate explicit cast.

It seems that vector is not much different:
```
std::simd v{data, element_aligned}; // no conversion - type can be potentially deduced
std::simd<float> v{data, element_aligned}; // vcvtpd2ps will be aligned with builtin type
auto v{ std::safe_cvt<std::simd<int>>( std::simd v{data, element_aligned} ) }; // adds safety to conversion, if such function is first introduced for scalars
```

**Comment by mattkretz** [comment]
> I am not sure that those examples reveal the "load" concept:

The examples in my previous answer are an answer to "What was the argument for making conversions inconsistent with builtin types?". I thought you meant conversions on broadcast when you asked that question.

> `std::copy` - example is more of memory-memory operation.

It could be. But really nothing requires anything to be in memory for all our examples so far. `std::copy` is simply an abstract way of copying from one range to another. And if it weren't for the requirement of ForwardIterators to return an actual lvalue reference on dereferencing, `simd<T>` would certainly be a range as well.

> scalar to `std::simd` - is about implicit conversion and not about loading.

Right, I showed why this conversion is different for `simd` compared to builtin types.

> When we are talking about load from memory the closest analog is
> 
> ```
> double* data;
> float x{data[0]};
> ```

I disagree. There fundamental difference is that `float` is oblivious to the fact that the value it is assigned comes from a contiguous array of doubles. Whereas `simd<float> x(data, element_aligned)` knows about the array. This is why I was looking for an operation which also has this information, leading me to `std::copy`.

> We are putting memory into scalar from memory.

Whether there's any *memory* load involved is neither required nor likely for small problems. It is a copy of a value, just like the `simd` load is a copy of multiple values. But in both cases, whether that's an actual load instruction is QoI.

> There are three operations here - first subscript operator data[0] then implicit converting then constructing scalar.
> If we want - non implicit conversion - we type it with a separate explicit cast.
> 
> It seems that vector is not much different:
> 
> ```
> std::simd v{data, element_aligned}; // no conversion - type can be potentially deduced
> std::simd<float> v{data, element_aligned}; // vcvtpd2ps will be aligned with builtin type
> auto v{ std::safe_cvt<std::simd<int>>( std::simd v{data, element_aligned} ) }; // adds safety to conversion, if such function is first introduced for scalars
> ```

I always wanted to design something closer to scalar subscripting, like:
```c++
using V = stdx::native_simd<float>;
void f(const std::vector<float>& data) {
  for (simd_subscript<V::size()> i = 0; i < data.size(); ++i) {
    V x = data[i];
    // ...
  }
}
```
In this case the analogy to scalar works better. Now `data[i]` basically becomes `stdx::fixed_size_simd<float, V::size()>` and the assignment operator is where the potential conversion happens. Now it's suddenly all about how conversions between objects of different `simd` specializations are defined. There's never a conversion on load.

**Comment by mattkretz** [comment]
@danieltowner We need to nail this down ASAP. `simd` loads and stores allow the pointer type to be any *vectorizable* type in the TS and P1928R2. I'm still like my original proposal above best.

**Comment by danieltowner** [comment]
I like being able to use any pointer type and have it convert to/from as required.

**Comment by mattkretz** [comment]
Sure. But my question is about
1. consistency
2. opt-in to conversions

There's no `static_cast` / explicit constructor call vs. implicit conversion for loads and stores as there is for simd to simd conversions and scalar to simd broadcasts...

**Comment by mattkretz** [comment]
I guess I'll be fine with documenting this inconsistency in P1928, without recommending any change to the status quo.

**Comment by mattkretz** [comment]
__POLL: Make `copy_to`/`copy_from`/load constructor only do value-preserving conversions by default, and require passing a flag to do non-value-preserving conversions.__

|Strongly Favor|Weakly Favor|Neutral|Weakly Against|Strongly Against|
|-|-|-|-|-|
|14|9|1|0|0|

So we need a new flag, i.e. a name to allow not-value-preserving conversions on loads & stores.
* `v.copy_to(ptr, std::simd_lossy_cvt)`
* `v.copy_to(ptr, std::simd_cvt)`
* `v.copy_to(ptr, std::simd_cvt_any)`
* `v.copy_to(ptr, std::simd_convert)`
* `v.copy_to(ptr, std::simd_lossy_cvt)`
* ...?

**Comment by iburyl** [comment]
v.copy_to(ptr, std::simd_convert) - this one looks good. There is no need to add the "lossy" part - we are already very explicitly intentional by typing "convert".

**Comment by mattkretz** [comment]
The next paper revision should list possible names and then argue for our preference/recommendation.
The reason why I think saying more than just "convert" is that you can already convert on loads and stores without the flag. I.e. the flag doesn't enable conversions per-se. It enables a certain subset of conversions.

**Comment by iburyl** [comment]
But we also sort of enforce coversion, where it was not possible without this flag.

**Comment by mattkretz** [comment]
I wouldn't say "enforce conversion". `v.copy_to(ptr, std::simd_convert)` where `ptr` is `v::value_type*` is still valid code. I.e. it doesn't make non-converting load/store ill-formed. It enables the subset of conversions that are otherwise ill-formed.

**Comment by mattkretz** [comment]
This is the load/store flag mechanism API similar to what I had in Vc. I was originally prepared to put at least also a *streaming* flag into the stdlib. The *prefetch* flag is very special, but when you need it, it can be very handy. Once we have the flag combining mechanism in place, we should be able to add *prefetch* later or as a vendor extension.

Anyway, we need an API for combining flags. So that's the idea. We wouldn't necessarily have to specify the whole mechanism.

https://compiler-explorer.com/z/h7Mszqz1r
```c++
namespace std {
namespace detail {
template <typename... Tags>
struct _Flags : Tags... {
    template <typename T0, typename... More>
    friend constexpr auto operator|(_Flags, _Flags<T0, More...>) {
        if constexpr ((std::same_as<Tags, T0> or ...)) {
            if constexpr (sizeof...(More))
                return _Flags<Tags...>{} | _Flags<More...>{};
            else
                return _Flags<Tags...>{};
        } else {
            if constexpr (sizeof...(More))
                return _Flags<Tags..., T0>{} | _Flags<More...>{};
            else
                return _Flags<Tags..., T0>{};
        }
    }
};

struct _Convert {
    static constexpr bool allow_any_conversion = true;
};

struct _Aligned {
    static constexpr bool is_simd_aligned = true;
};

template <std::size_t N>
struct _Overaligned {
    static constexpr int overalignment = N;
};

struct _Streaming {
    static constexpr bool is_streaming = true;
};

template <int L1, int L2 /*, exclusive vs. shared*/>
struct _Prefetch {
    static constexpr int prefetch_L1 = L1;
    static constexpr int prefetch_L2 = L2;
};

}  // namespace detail

// public / specified API:
inline constexpr detail::_Flags<> default_flags;

inline constexpr detail::_Flags<detail::_Convert> simd_convert;

inline constexpr detail::_Flags<detail::_Aligned> simd_aligned;

template <std::size_t N>
    requires(std::has_single_bit(N))
inline constexpr detail::_Flags<detail::_Overaligned<N>> overaligned;

inline constexpr detail::_Flags<detail::_Streaming> simd_streaming;

template <int L1, int L2>
inline constexpr detail::_Flags<detail::_Prefetch<L1, L2>> prefetch;

// demo:
void simd_load(auto x) {
    if constexpr (requires { x.prefetch_L1; })
        asm("prefetch %0 %1" ::"i"(x.prefetch_L1), "i"(x.prefetch_L2));

    if constexpr (requires { x.overalignment; })
        asm volatile("overalign to %0" ::"i"(x.overalignment));
    else if constexpr (requires { x.is_simd_aligned; })
        asm volatile("aligned load/store");
    else
        asm volatile("unaligned load/store");

    if constexpr (requires { x.allow_any_conversion; })
        asm volatile("allow all conversions");
    else
        asm volatile("only value-preserving conversions");

    if constexpr (requires { x.is_streaming; })
        asm volatile("use streaming load/store");

    asm volatile("-----------");
}

}  // namespace std

void test() {
    std::simd_load(std::default_flags);
    std::simd_load(std::overaligned<4096> | std::simd_streaming);
    std::simd_load(std::prefetch<4, 8>);
    std::simd_load(std::prefetch<4, 8> | std::simd_aligned);
    std::simd_load(std::prefetch<4, 8> | std::simd_aligned | std::simd_convert |
                   (std::overaligned<4096> | std::simd_aligned));
}
```

**Comment by danieltowner** [comment]
It is a neat mechanism, but does it belong in std::simd? It feels like a solution to a problem that could appear elsewhere, including in user's own source code and libraries, so should it be made more generic in a paper of its own?

**Comment by mattkretz** [comment]
You mean the streaming and prefetch flags? I'm not proposing them again (at this point anyway). I just wanted to note that we need a mechanism to combine flags at compile time (into a new type). We need it if we ever want to extend the flags. We need it because I'm supposed to add a "convert" flag.

**Comment by mattkretz** [comment]
BTW, the comment/reason to exclude a "streaming" load/store flag back in 2014 was that there could be a more general mechanism so we don't want to clutter `simd` with it. I agree in general except
1. streaming loads and store are typically used together with SIMD
2. it's been 10 years and no such general mechanism has materialized

So, I'd at least be interested in allowing implementation-defined flags if WG21 isn't interested in a standard streaming flag...

**Comment by mattkretz** [comment]
load store flags for conversions were accepted by LEWG
